#!/bin/sh

if [ $3 ];then

    ft=`echo "122"`
    sd=`echo "1111010"`
    th=`echo "-123"`

    if [ $1 = $ft ];then
        echo 1111010
    elif [ $1 = $sd ];then
        echo 122
    else
        echo -7B
    fi
else
    echo
fi