##
## Makefile for  in /home/exam/rendu/ex_5
## 
## Made by Exam User
## Login   <exam@epitech.net>
## 
## Started on  Mon Jan  4 10:29:23 2016 Exam User
## Last update Mon Jan  4 10:29:24 2016 Exam User
##

all : name

name :
	gcc -o url_encode main.c

clean :
	rm -f main.o

fclean : clean
	rm -f url_encode

re: fclean all
